version: "3"

services:
  cmblensing:
    image: marius311/cmblensing.jl:${TAG:-stable}
    build:
      context: .
    ports:
     - "${PORT:-8888}:${PORT:-8888}"
    hostname: localhost
    environment:
     - PORT=${PORT:-8888}
