name: runtests

on: [push, pull_request]

jobs:
  main:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental == 'nightly' }}
    timeout-minutes: 20
    strategy:
      matrix:
        julia-version: ['1.3', '1.4','nightly']    
        os: [ubuntu-latest]
        JULIA_FFTW_PROVIDER: ['MKL'] # would be nice to get FFTW working too
      fail-fast: false
    env:
      PYTHON: python3

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - run: >
          sudo apt-get install --no-install-recommends gfortran python3-setuptools python3-wheel
          && pip3 install camb
      - uses: julia-actions/julia-runtest@master
        env:
          JULIA_FFTW_PROVIDER: ${{ matrix.JULIA_FFTW_PROVIDER }}
